'use client';

import { ServerStyleSheet } from 'styled-components';
import AppLayout from '@/ui/AppLayout';
import { ReactQueryProvider } from './providers/ReactQueryProvider';
import GlobalStyles from '../styles/GlobalStyles.js';

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  const sheet = new ServerStyleSheet();
  const styles = sheet.getStyleElement();

  return (
    <html lang="en">
      <head>{styles}</head>
      <body>
        <ReactQueryProvider>
          <GlobalStyles />
          <AppLayout>{children}</AppLayout>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
