// src/app/layout.js (Server Component)
import GlobalStyles from '@/styles/GlobalStyles';
import StyledComponentsRegistry from '@/styles/StyledComponentsRegistry';
import AppLayout from '@/ui/AppLayout';
import { ReactQueryProvider } from './providers/ReactQueryProvider';

export const metadata = {
  title: 'Odyssey Leads',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <GlobalStyles />
          <AppLayout>
            <ReactQueryProvider>{children}</ReactQueryProvider>
          </AppLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
